# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f63ad6fe9c41731279e2ca1ef7d616bb6b00dd23676fd9589523f8710fef83b89d82a895fda196236e8da716747e7005eaea814d7a83db02103936e30222fe3

test:
  secret_key_base: c26502591fb262313c57ea720d99c84e94532c6cea23566f0966abd52cc6116d440016890ff3b1b1ac240eed074ed0f435896247f2dc6954594c76780c965240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
